### ISSUE TITLE
Components API Reference

### ISSUE THREAD

**Issue by carlomigueldy** [nuxt-community/nuxt7#105]
Hello,

Is there any documentation for me to know how to use the UI components nuxt7 provides?

**Comment by D-Marc1** [comment]
Nuxt7 is a wrapper over Framework7. You can check out the docs for Framework7 Vue here: https://framework7.io/vue/.

**Comment by carlomigueldy** [comment]
> Nuxt7 is a wrapper over Framework7. You can check out the docs for Framework7 Vue here: https://framework7.io/vue/.

Thank you. I actually realized that one a week after I posted this issue.
