### ISSUE TITLE
Cannot set property $nuxt of #<Vue> which has only a getter

### ISSUE THREAD

**Issue by 1isten** [nuxt-community/nuxt7#115]
Just tried to create a new fresh project with `npx sao@1 -u nuxt-community/nuxt7 nuxt7-app`, and `yarn dev` I got this error:

<img width="1389" alt="Screen Shot 2020-10-20 at 5 10 38" src="https://user-images.githubusercontent.com/11518941/96565866-7db26f00-12f7-11eb-9886-6cd967b374de.png">

node: v10.22.0
yarn: v1.22.4
nuxt: v2.14.7
framework7: v5.7.13

**Comment by twnaing** [comment]
I am also encountering this error with

@vue/core@2.14.11
nuxt7@latest: version "4.0.1"
framework7-vuew@^5.7.0
framework7@^5.7.0

The pull request also does fix for me.

**Comment by ericforgues** [comment]
The same here and the PR fixes the problem well.

Do you know when they will be merged?

**Comment by mpuz** [comment]
same problem
