### ISSUE TITLE
Path problem in windows.

### ISSUE THREAD

**Issue by relzhong** [nuxt-community/nuxt7#13]
In .nuxt/App.js, the mateial-icon.css path is wrong .
![default](https://user-images.githubusercontent.com/12643564/32942107-f0a8144e-cbc2-11e7-9e63-278c9964b526.png)

I think resolvePath in module.js cause this problem.
![default](https://user-images.githubusercontent.com/12643564/32942140-0e430cde-cbc3-11e7-8efd-37a368b9113f.png)

**Comment by pi0** [comment]
Shipped in v0.8.3.
