### ISSUE TITLE
nuxt generate fail on win10

### ISSUE THREAD

**Issue by relzhong** [nuxt-community/nuxt7#15]
I run `npm run generate` in nuxt7's template directory.
How ever i get error like this: 
`ERROR in app.abd666e0ab7b86ce9f4e.js from UglifyJs
Unexpected token: name (_typeof) [app.abd666e0ab7b86ce9f4e.js:2752,7]
 TypeError: __webpack_require__(...) is not a function`
node v8.9.0 
npm v5.5.1

I run the same code on linux mint, it can generate successfully.

**Comment by pi0** [comment]
ُThis bug with windows may be with [this](https://github.com/nuxt-community/nuxt7/blob/master/lib/module.js#L164) line as windows use backslashes. I'll check it soon.

**Comment by pi0** [comment]
Hi. This will be fixed soon with 1.0.0 release.
