### ISSUE TITLE
use $router.push to navigate

### ISSUE THREAD

**Issue by relzhong** [nuxt-community/nuxt7#16]
I set router mode to `hash`,  and I use $router.push to navigate my page, but if I print $router, it appear that the $router is in `history` mode. 
 
![image](https://user-images.githubusercontent.com/12643564/33121311-503632b6-cfaf-11e7-8ff3-2453bc8b2cfc.png)

in nuxt.config.js.
`  router: {
    mode: 'hash',
    base: pathBase,
  }, `
` framework7: {
    mode: 'hash',
  },
`

At first I try to use history mode, but I can't add base path to router.

**Comment by pi0** [comment]
Hi. We have to use framework7 router ($f7Router) for navigation.

**Comment by 294650171** [comment]
how to use $f7Router in methods?
