### ISSUE TITLE
How to properly register routes with params?

### ISSUE THREAD

**Issue by thugic** [nuxt-community/nuxt7#23]
I am dynamically fetching data from an API so when I go to '/something/1234' it gets me data from a server where id=1234 and in F7-Vue I managed that pretty well.

I tried to do that in nuxt7 but it doesn't open any page ...

In F7-Vue you just add:

```
`routes: [
   {
     path: '/something/:id',
     componentUrl: 'pages/something.vue',
  }
]`
```

I tried to add that in nuxt.config.js but no luck ....

Any help?

Thanks guys

**Comment by nolimits4web** [comment]
No, componentUrl can’t be used with Vue components, as Vue single file components require server side compilation. Just use it in same way as in F7-Vue with just a “component”

**Comment by pi0** [comment]
All routes (including dynamic routes) are auto-generated by the structure of pages directory. (The same way as defining them with Nuxt.js). Please take a look at [with params](https://github.com/nuxt-community/nuxt7/tree/master/examples/with-params) example.

**Comment by thugic** [comment]
Thanks you, but how do you manage multiple params this way?
Let's say I have /user/:year/:id 
(One solution I could use here is /user/year.id and then explode the params but I don't really like it that way)

**Comment by pi0** [comment]
Simply creating `pages/_year/_id.vue` the file will do the trick to make a URL like http://localhost:3000/blog/2017/5

I've updated with params example too: https://github.com/nuxt-community/nuxt7/tree/master/examples/with-params

**Comment by thugic** [comment]
Great thank you!
