### ISSUE TITLE
middleware

### ISSUE THREAD

**Issue by rhoseno98** [nuxt-community/nuxt7#24]
Hi, 

how to use nuxt middleware on this nuxt7 ?

**Comment by zoosky** [comment]
It seems not to work.

**Comment by 294650171** [comment]
how to use nuxt middleware on nuxt7

**Comment by kungfoo** [comment]
I agreee, it seems not to work. Middleware code is never called when you use the vanilla nuxt way of adding it.

**Comment by pi0** [comment]
Hi. Unforoutanly because of the custom router that framework7 uses, we can't offer middleware. You can use a nuxt plugin for this to get it working. `$nuxt.$f7` allows accessing to framework7 instance too.
