### ISSUE TITLE
Cannot install: ENOENT no such file or directory

### ISSUE THREAD

**Issue by Hexodus** [nuxt-community/nuxt7#27]
I was so excited to find out that there indeed is a F7 Nuxt integration. That's so great, I thought ... but  my very first attempt to install failed. Any ideas why?

```
npx sao nuxt-community/nuxt7 nuxt7-app

C:\Users\adria\AppData\Roaming\npm-cache\_npx\11096\node_modules\sao\bin\sao
error Error: ENOENT: no such file or directory, link 'E:\REPO\_Vue.js Udemy\_nuxt\home.vue' -> 'C:\Users\adria\.sao\repos\nuxt-community%%nuxt7\examples\kitchen-sink\pages\index.vue'
```

**Comment by pi0** [comment]
Hi. Windows problem should have been resolved. Would you please try again and ping me if having problems?
