### ISSUE TITLE
Installation with Yarn only without npx [enhancement|

### ISSUE THREAD

**Issue by Hexodus** [nuxt-community/nuxt7#28]
I feel that there should be a way to use Yarn to install nuxt7 like there is a way to install create nuxt app:
```
npx create-nuxt-app <my-project>
yarn create nuxt-app <my-project>
```
[nuxt-community/create-nuxt-app](https://github.com/nuxt-community/create-nuxt-app)

**Comment by pi0** [comment]
Hi. Thanks for the suggestion. We are working on a built-in scaffolding solution for nuxt cli. Until then the only possible method is sao for the nuxt7 template.
