### ISSUE TITLE
Add me to nuxt-community GitHub Org

### ISSUE THREAD

**Issue by YoginthS** [nuxt-community/nuxt7#31]
Hey,

I am really excited about the active development and wanted to be a part of the **nuxt-community** organization on GitHub. In this regard, how can I become a member and would love if somebody would add me to it?

My GitHub username is **YoginthS**

Thanks, Yoginth

**Comment by clarkdo** [comment]
Hi @YoginthS, thank you for attention, we really hope that more and more friends to join our community and make Nuxt better and better together.

Firstly, I think you can help to solve the [issues](https://github.com/search?q=org%3Anuxt-community+&type=Issues) in community.

Or submit effective pull requests actively, create practicable repositories in nuxt-community.

If you have shown enough efforts and contributions in community, I think @Atinux will very welcome you to join our outstanding team. 😸 

/cc @Atinux @alexchopin @pi0

**Comment by Atinux** [comment]
Completely agree with @clarkdo, we would love to add you on Community, of course we need at first to see your contributions by helping out on issues & PRs :)

Please ping us (@pi0, @clarkdo and myself) for any PR or issues where you need help from us!
