### ISSUE TITLE
phonegap/cordova

### ISSUE THREAD

**Issue by janhox** [nuxt-community/nuxt7#32]
Hi, first of all many thanks for this great starter template.
However I am struggling to test my basic app via phonegap serve/developer app. 
Is there any tutorial that you can recommend describing the build process from npm run generate to running the app locally for testing ?
Thanks for your input.

**Comment by pi0** [comment]
Hi @janhox. This module is primarily designed to make a fully PWA compatible web app. You have to use standard `nuxt generate` to generate a static version of the project and then can use https://appmaker.xyz to make APK of it.
