### ISSUE TITLE
No asyncData?

### ISSUE THREAD

**Issue by cyberiaa** [nuxt-community/nuxt7#33]
Hi Pooya,

Happy Norouz! Thanks for your great work, 

I couldn't make asyncData work with nuxt7. I know there is no SSR here but having asyncData make porting Nuxt apps a lot easier.

I don't know if it's an intentionally feature or I did something wrong.

**Comment by mwargan** [comment]
I'm also running into this issue. How do we fetch data before a page loads? beforeRouteEnter also doesn't seem to be called...

**Comment by pi0** [comment]
Hi @cyberiaa. Sorry for the late answer. Unfortunately, Framework7 has it's own router which doesn't support asyncData. You have to create basic state in `data` and fill it with `async mounted()`
