### ISSUE TITLE
Include only some Components from Framework 7 in build process

### ISSUE THREAD

**Issue by bushbill** [nuxt-community/nuxt7#39]
Is it possible to include only some components (from https://github.com/framework7io/Framework7/blob/master/scripts/build-config.js)

How can I do this in the config section framework7.build in nuxt.config.js?

Otherwise the resulting css files are too big!

**Comment by bushbill** [comment]
I think, it is not possible to overwrite the parameter build.components with the function defaultsDeep from loadash. Maybe same for md.colors, too.

Possible solution: Extend framework7 Options with components and handle it correctly in nuxt7/lib/module.js

**Comment by pi0** [comment]
Hi @bushbill. Sorry for late answer and thanks for your hint. DefaultsDeep usage removed in the flavor of `defu`. `components` array is now overrideable.
