### ISSUE TITLE
Side Panels NOT WORKING (ks)

### ISSUE THREAD

**Issue by bozzzi** [nuxt-community/nuxt7#40]
In kitchen sink demo side panels are not working. Anybody can post code example to make it work? Do I need to include it in default template render fn?

**Comment by bozzzi** [comment]
Update:

With html code in /lib/templates/layouts/default.vue

`<template>
  <div id="app">
    <f7-statusbar></f7-statusbar>
    <f7-panel left cover>
      <f7-view url="/panel-left/"></f7-view>
    </f7-panel>
    <f7-panel right reveal>
      <f7-view url="/panel-right/"></f7-view>
    </f7-panel>
    <f7-view url="/" id="main" :main="true" class="ios-edges"></f7-view>
  </div>
</template>`

Side panels are actually working but both panels opens index page even **url="/panel-left/"** is set. In routes **panel-left** is linked to **panel-left.vue** file from **/pages** folder.
I'm new in vue and nuxt... Is there any other way to set url for panel?

**Comment by naelrouz** [comment]
Hi! I create in root directory "layouts/default.vue" with code 

> <template lang="pug">
  #app
    nuxt
    
    // Left Panel with Reveal effect
    f7-panel(left='' reveal='')
      f7-view
        f7-page
    //- app-left-panel
    // Right Panel with Cover effect and dark layout theme
    f7-panel(right='' theme-dark='')
      f7-view
        f7-page
          f7-block Right panel content
    // Main view
    f7-view(main='')
</template>



<script>
import { f7View, f7Statusbar } from 'framework7-vue';

// import appLeftPanel from '@/components/left-panel/LeftPanel.vue';

export default {
  name: 'f7-layout',
  components: {
    f7View,
    f7Statusbar,
    appLeftPanel
  }
  // render(h) {
  //   return h('div', [h('f7-statusbar'), h('nuxt')]);
  // }
};
</script>

 [About Nuxt templates](https://ru.nuxtjs.org/guide/layouts)

**Comment by WildSunLove** [comment]
I've been running into the same issue. Has anyone else run into this and found any fixes?

**Comment by WildSunLove** [comment]
So I notice that if I load the page from the index, the panels display their content fine.
However, if I navigate to something, such as `/about` and then I refresh, now the panel views will mirror the main content.

Flummoxed by this, not sure if this is something I can fix in my code or if there is a bug within nuxt7.

**Comment by WildSunLove** [comment]
So I have an inkling of what is going on here.
I think when the page is reloaded, it grabs the URL for whatever page is loaded and populates that into the view.
However, it should only populate it into the main view, but it seems to be doing it for all the views.

If I change the panels to not be a view this kind of fixes it.
Like so:
```
<f7-panel right>
  <f7-page>
    ...
  </f7-page>
</f7-panel>
```

However, it not being a view seems to limit certain functionality, like it doesn't detect hover over links.

**Comment by WildSunLove** [comment]
Actually, scratch that, I just didn't have my thing set as an <f7-link> thus the hover not working.

Ya I think this solution works well for now. Changing it so it is not wrapped in an f7-view, such that the only f7-view is the main one.

This doesn't allow the usefulness of having an f7-view draw from a particular URL but for the time being this is the best solution I've found and it works well for me in my use case.

**Comment by pi0** [comment]
Hi. Sorry for delay answering. Nuxt7 was not being maintained for some months. The latest version is based on framework7@4.x with a working KS example for side panels.  @bozzzi answer is almost correct. We can use a layout to make it work.

https://github.com/nuxt-community/nuxt7/tree/master/examples/kitchen-sink/layouts

PS: If anyone interested to make a PR to improve the docs for side-panel that would be more than welcome and please open a new issue if still having problems :+1:

**Comment by ansidev** [comment]
@pi0 Currently, the left panel is working but the right panel is not. It can only be opened once.
You can see it in nuxt7 kitchen sink demo.
