### ISSUE TITLE
How to change default build colors?

### ISSUE THREAD

**Issue by na86** [nuxt-community/nuxt7#41]
Hi guys, thanks for this beautiful framework
i'm trying to change the default colors using the framework7 build parameter in my nuxt.config.js file, but nothing happen. 

any ideas?
thanks in advance

Nd

**Comment by pi0** [comment]
Hi. Sorry for such a late answer. Please consider upgrading to v3 and checking docs. The [colors](https://github.com/nuxt-community/nuxt7#colors) options is available. (For v2, it should be `build.colors`)
