### ISSUE TITLE
[Question]how to render routable tab component using import keyword 

### ISSUE THREAD

**Issue by alterhu2020** [nuxt-community/nuxt7#55]
I saw the example in this repository had showed the `tab` functionality with `content` option, that works well, but if  the tab content using another vue component file by component option provided by framework7, it seems that it had not rendered the dynamic vue page ,like the below code: 

``` 
   mode: 'history',
    themeColor: 'green',
    darkTheme: false,
    mdIcons: false,
    invertNav: false,
    disableContextMenu: true,
    disableSelect: true,
    routes: {
      'index': {
        tabs: [
          { path: '/', id: 'home', component:  import('../layouts/MobileTabLayout/tabs/Home.vue').then(m => m.default) },
          { path: '/ucenter', id: 'usercenter', component: 'import('../layouts/MobileTabLayout/tabs/Ucenter.vue').then(m => m.default) }
        ]
      }
    }

```

 could you help me taking a review this issue and how can I solve it ?
appreciated that very much if you can help me.  @pi0  @clarkdo @zoosky

**Comment by pi0** [comment]
Hi. I've added routable-tabs example: https://github.com/nuxt-community/nuxt7/tree/master/examples/routable-tabs
