### ISSUE TITLE
Nuxt default 404 error.vue page not works

### ISSUE THREAD

**Issue by alterhu2020** [nuxt-community/nuxt7#56]
The problem is very simple, If we put the `error.vue` file in `layout` folder, when we visit a page never existing, then it will not navigate to the default `errro.vue` page content.

@pi0 , Do you have time to fix it ?

**Comment by pi0** [comment]
Hi, @alterhu2020. Sorry for the late update. This is possible now by creating `pages/default.vue`. Example:  https://github.com/nuxt-community/nuxt7/blob/master/template/pages/default.vue
