### ISSUE TITLE
Cannot support this.$f7router.navigate({name: 'index'})

### ISSUE THREAD

**Issue by alterhu2020** [nuxt-community/nuxt7#57]
I saw the generated router path  using two property: name and component, it has not the name property, which will cause that we cannot use the router name functionality . thanks .

**Comment by alterhu2020** [comment]
with pull request link: https://github.com/nuxt-community/nuxt7/pull/58

**Comment by alterhu2020** [comment]
close it as the pull request: #58

**Comment by pi0** [comment]
released in v3.1.0
