### ISSUE TITLE
EJS error on install

### ISSUE THREAD

**Issue by sts-ryan-holton** [nuxt-community/nuxt7#64]
Hi 👋 

I'm trying to install this via: `npx sao nuxt-community/nuxt7 nuxt7-app` and I'm getting an error:

```
error ReferenceError: ejs:1
name is not defined
```

<img width="826" alt="Screenshot 2019-05-04 at 11 24 30" src="https://user-images.githubusercontent.com/25177538/57177736-33b59f00-6e5f-11e9-8d0e-63be0727b707.png">

Node JS: v10.13.0
NPM: 6.9.0

**Comment by siberiadev** [comment]
Same problem here

**Comment by a-j-n** [comment]
Same proplem here 
<img width="950" alt="Screen Shot 2019-05-16 at 10 55 56 PM" src="https://user-images.githubusercontent.com/34508885/57886576-cfff7e80-782d-11e9-99a4-22ea0eb7b1c9.png">

**Comment by vuiprime** [comment]
Same problem here
![image](https://user-images.githubusercontent.com/43124315/57898154-141c6e80-7882-11e9-9811-80dff72e05b5.png)

NodeJS : v11.3.0
Npm : 6.9.0
Ubuntu : 18.04

**Comment by pi0** [comment]
Sorry for inconveniences. SAO had breaking changes. This should be resolved with the latest commit. Please try:

```
npx sao@1 -u nuxt-community/nuxt7 nuxt7-app
```
