### ISSUE TITLE
Can't  install -  ENOENT no such file or directory ...... (Windows 10)

### ISSUE THREAD

**Issue by nazmulpro** [nuxt-community/nuxt7#85]
I am getting the following error when trying to create a new app from starter template:

![Capture](https://user-images.githubusercontent.com/1936844/67929124-c9e83900-fbe6-11e9-8581-0f6e2ccb32e3.PNG)

Thanks

**Comment by nazmulpro** [comment]
anyone ??? @pi0

**Comment by robotpapier** [comment]
Hi, I think you have to copy the content of 404.vue and paste and replace the content of default.vue as in windows there are no symbolic links
